package org.apache.jsp.pages.datastandard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class standardCategory_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/common/dialog1.jsp");
  }

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String CONTEXT_PATH = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<title>广东省信息所（数据应用系统）</title>\r\n");
      out.write("\t<meta http-equiv=\"x-ua-compatible\" content=\"ie=7\" /> \r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(CONTEXT_PATH);
      out.write("dhtmlxSuite/dhtmlx/dhtmlx.css\" />\r\n");
      out.write("   <script src=\"");
      out.print(CONTEXT_PATH);
      out.write("dhtmlxSuite/dhtmlx/dhtmlx.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("   <script language=\"javascript\" src=\"");
      out.print( CONTEXT_PATH);
      out.write("js/date_validate.js\"></script>\t\r\n");
      out.write("\t<script language=\"javascript\" src=\"");
      out.print( CONTEXT_PATH);
      out.write("js/ctrl_util.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( CONTEXT_PATH);
      out.write("/css/main.css\" />\r\n");
      out.write("\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\thtml, body {width:100%; height:100%; margin:0px; padding:0px; overflow:hidden;}\r\n");
      out.write("\t</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("\t<div id=\"div_main\" style=\"position:relative;top:0;left:0;width:100%;height:100%;\"></div>\r\n");
      out.write("\t<div id=\"div_left\" style=\"position:relative;background-color:#e8f0f8;top:0;left:0;width:100%;height:100%\"></div>\r\n");
      out.write("\t<div id=\"div_right\" style=\"position:relative;top:0;left:0;width:100%;height:100%;\">\r\n");
      out.write("\t\t<div id=\"div_grid\" style=\"position:relative;top:0;left:0;width:100%;height:99%;overflow:auto;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t  var dhxWins = new dhtmlXWindows();\r\n");
      out.write("    dhxWins.enableAutoViewport(true);\r\n");
      out.write("    dhxWins.setImagePath(\"");
      out.print(CONTEXT_PATH);
      out.write("dhtmlxSuite/dhtmlxWindows/codebase/imgs/\");\r\n");
      out.write("    \r\n");
      out.write("    var winName=\"win\";  \r\n");
      out.write("    var editMode;       \r\n");
      out.write("    \r\n");
      out.write("    function openWindow(title,urlink,width,height){\r\n");
      out.write("       var w = dhxWins.createWindow(winName, 0, 0, width, height);\r\n");
      out.write("       w.setText(title);\r\n");
      out.write("       w.keepInViewport(true);\r\n");
      out.write("       w.setModal(true);\r\n");
      out.write("       w.centerOnScreen();\r\n");
      out.write("       //w.button(\"minmax1\").hide();\r\n");
      out.write("       //w.button(\"minmax2\").hide();\r\n");
      out.write("       w.button(\"park\").hide();\r\n");
      out.write("       w.attachURL(urlink);\r\n");
      out.write("       return w;    \r\n");
      out.write("    }\r\n");
      out.write("    function openSingleWindow(title,divhtml,width,height){\r\n");
      out.write("       if(height==null || height=='')\r\n");
      out.write("       \t\theight=100;\r\n");
      out.write("       \tif(width==null || width=='')\r\n");
      out.write("       \t\twidth=300;\r\n");
      out.write("   \t   var win2 = dhxWins.createWindow(winName, 0, 0, width, height);\r\n");
      out.write("       win2.setText(title);\r\n");
      out.write("       win2.keepInViewport(true);\r\n");
      out.write("       win2.setModal(true);\r\n");
      out.write("       win2.centerOnScreen();\r\n");
      out.write("       //win2.button(\"minmax1\").hide();\r\n");
      out.write("      // win2.button(\"minmax2\").hide();\r\n");
      out.write("       win2.button(\"park\").hide();\r\n");
      out.write("       win2.attachHTMLString(divhtml);\r\n");
      out.write("       return win2;    \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function openWindowById(title,objId,width,height){\r\n");
      out.write("\t       if(height==null || height=='')\r\n");
      out.write("\t       \t\theight=100;\r\n");
      out.write("\t       \tif(width==null || width=='')\r\n");
      out.write("\t       \t\twidth=300;\r\n");
      out.write("\t   \t   var win2 = dhxWins.createWindow(winName, 0, 0, width, height);\r\n");
      out.write("\t   \t   win2.button(\"close\").attachEvent(\"onClick\", function(){\r\n");
      out.write("\t   \t\tdhxWins.window(winName).close();\r\n");
      out.write("\t\t   \t   });\r\n");
      out.write("\t   \t   win2.maximize();\r\n");
      out.write("\t       win2.setText(title);\r\n");
      out.write("\t       win2.keepInViewport(true);\r\n");
      out.write("\t       win2.setModal(true);\r\n");
      out.write("\t       win2.centerOnScreen();\r\n");
      out.write("\t       win2.button(\"minmax1\").hide();\r\n");
      out.write("\t       win2.button(\"minmax2\").hide();\r\n");
      out.write("\t       win2.button(\"park\").hide();\r\n");
      out.write("\t       win2.attachObject(objId);;\r\n");
      out.write("\t       return win2;    \r\n");
      out.write("\t    }\r\n");
      out.write("   \r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\tfunction closedialog(ret){\r\n");
      out.write("\t\t\tdhxWins.window(winName).close();\r\n");
      out.write("\t\t\tif(ret=='true') {\r\n");
      out.write("\t\t\t\tvar curId = tree.getSelectedItemId();\r\n");
      out.write("\t\t\t\tif(editMode==\"ADD\") {\r\n");
      out.write("\t\t\t\t\ttree.refreshItem(curId);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if(editMode==\"EDIT\"){\r\n");
      out.write("\t\t\t\t\tvar parentId = tree.getParentId(curId);\r\n");
      out.write("\t\t\t\t\ttree.refreshItem(parentId);\r\n");
      out.write("\t\t\t\t\ttree.selectItem(curId,false,\"\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse if(editMode==\"DELETE\"){\r\n");
      out.write("\t\t\t\t\tvar parentId = tree.getParentId(curId);\r\n");
      out.write("\t\t\t\t\ttree.refreshItem(parentId);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\teditMode=\"\";\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction addCategory(nodeId){\r\n");
      out.write("\t\t\tif (nodeId!=\"\"){\r\n");
      out.write("\t\t\t\teditMode=\"ADD\";\r\n");
      out.write("\t\t\t\tvar url_link=\"");
      out.print( CONTEXT_PATH);
      out.write("datastandard/standardCategory.do?action=\"+editMode+\"&pid=\"+nodeId;\r\n");
      out.write("\t\t\t\topenWindow(\"增加分类\",url_link,700,400);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction modifyCategory(nodeId){\r\n");
      out.write("\t\t\tif (nodeId!=\"root\") {\r\n");
      out.write("\t\t\t\tif (nodeId==\"\"||nodeId==null) {\r\n");
      out.write("\t\t\t\t\talert(\"请选择分类！\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\teditMode=\"EDIT\";\r\n");
      out.write("\t\t\t\tvar url_link=\"");
      out.print( CONTEXT_PATH);
      out.write("datastandard/standardCategory.do?action=\"+editMode+\"&id=\"+nodeId;\r\n");
      out.write("\t\t\t\topenWindow(\"修改分类\",url_link,700,400);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction deleteCategory(nodeId){\r\n");
      out.write("\t\t\tif (nodeId!=\"root\") {\r\n");
      out.write("\t\t\t\tvar res=confirm(\"真的要删除该分类？\");\r\n");
      out.write("\t\t\t\tif(res==false) return;\r\n");
      out.write("\t\t\t\teditMode=\"DELETE\";\r\n");
      out.write("\t\t\t\tvar url_link=\"");
      out.print( CONTEXT_PATH);
      out.write("datastandard/standardCategory.do?action=\"+editMode+\"&id=\"+nodeId;\r\n");
      out.write("\t\t\t\tvar loader = dhtmlxAjax.postSync(url_link,\"\");\r\n");
      out.write("\t\t\t\tvar ret=loader.xmlDoc.responseText;\r\n");
      out.write("\t\t\t\tvar obj = eval('(' + ret + ')');\r\n");
      out.write("\t\t\t\tif(obj.exit==\"0\"){\r\n");
      out.write("\t\t\t\t   tree.deleteItem(nodeId);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\telse{\r\n");
      out.write("\t\t\t\t   showMessage(obj.message);\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t    \t\teditMode=\"\";\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction setButtonVisible(id){\r\n");
      out.write("\t\t\ttoolbar.disableItem(\"new_Category\");\r\n");
      out.write("\t\t\ttoolbar.disableItem(\"modify_Category\");\r\n");
      out.write("\t\t\ttoolbar.disableItem(\"del_Category\");\r\n");
      out.write("\t\t\tif (id==\"root\") {\r\n");
      out.write("\t\t\t\ttoolbar.enableItem(\"new_Category\");\r\n");
      out.write("\t\t\t\ttoolbar.disableItem(\"modify_Category\");\r\n");
      out.write("\t\t\t\ttoolbar.disableItem(\"del_Category\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (id!=\"\") {\r\n");
      out.write("\t\t\t\ttoolbar.enableItem(\"new_Category\");\r\n");
      out.write("\t\t\t\ttoolbar.enableItem(\"modify_Category\");\r\n");
      out.write("\t\t\t\ttoolbar.enableItem(\"del_Category\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar dhxLayout = new dhtmlXLayoutObject(\"div_main\", \"1C\");\r\n");
      out.write("\t\tvar toolbar = dhxLayout.attachToolbar();\r\n");
      out.write("\t\ttoolbar.setIconsPath(\"");
      out.print( CONTEXT_PATH);
      out.write("images/icon/\");\r\n");
      out.write("\t\ttoolbar.addButton(\"new_Category\", 0, \"添加分类\", \"home--plus.gif\", \"home--plus.gif\");\r\n");
      out.write("\t\ttoolbar.addButton(\"modify_Category\", 1, \"修改分类\", \"home--pencil.gif\", \"home--pencil.gif\");\r\n");
      out.write("\t\ttoolbar.addButton(\"del_Category\", 2, \"删除分类\", \"home--minus.gif\", \"home--minus.gif\");\r\n");
      out.write("\t\ttoolbar.attachEvent(\"onClick\", function(id){\r\n");
      out.write("\t\t\tvar nodeId=tree.getSelectedItemId();\r\n");
      out.write("\t\t\tif(id==\"new_Category\") addCategory(nodeId);\r\n");
      out.write("\t\t\telse if(id==\"modify_Category\") modifyCategory(nodeId);\r\n");
      out.write("\t\t\telse if(id==\"del_Category\") deleteCategory(nodeId);\r\n");
      out.write("    \t});\r\n");
      out.write("    \t//dhxLayout.hideToolbar();\r\n");
      out.write("    \ttoolbar.disableItem(\"new_Category\");\r\n");
      out.write("    \ttoolbar.disableItem(\"modify_Category\");\r\n");
      out.write("    \ttoolbar.disableItem(\"del_Category\");\r\n");
      out.write("    \t\r\n");
      out.write("    \tdhxLayout.setSkin(\"dhx_skyblue\");\r\n");
      out.write("    \tvar leftPanel=dhxLayout.cells(\"a\");\r\n");
      out.write("//    \tvar rightPanel=dhxLayout.cells(\"b\");\r\n");
      out.write("    \tleftPanel.hideHeader();\r\n");
      out.write("    \tleftPanel.attachObject(\"div_left\");\r\n");
      out.write("    \tleftPanel.setWidth(250);\r\n");
      out.write("//    \trightPanel.hideHeader();\r\n");
      out.write("//    \trightPanel.attachObject(\"div_right\");\r\n");
      out.write("\r\n");
      out.write("\t\tvar tree = new dhtmlXTreeObject(\"div_left\",\"100%\",\"100%\",0);\r\n");
      out.write("\t\ttree.setImagePath(\"");
      out.print( CONTEXT_PATH);
      out.write("dhtmlxSuite/dhtmlx/imgs/csh_bluefolders/\");\r\n");
      out.write("\t\ttree.setSkin(\"dhx_blue\");\r\n");
      out.write("\t\ttree.attachEvent(\"onSelect\", function(id){\r\n");
      out.write("\t\t\tsetButtonVisible(id);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\ttree.attachEvent(\"onDblClick\", function(id){\r\n");
      out.write("\t\t\tmodifyCategory(id);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\ttree.attachEvent(\"onMouseIn\", function(id){\r\n");
      out.write("\t\t\tvar str=tree.getUserData(id,\"name\");\r\n");
      out.write("\t\t\ttree.setItemText(id,\"<font color='#FF4422'>\"+str+\"</font>\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\ttree.attachEvent(\"onMouseOut\", function(id){\r\n");
      out.write("\t\t\tvar str=tree.getUserData(id,\"name\");\r\n");
      out.write("\t\t\ttree.setItemText(id,str);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\ttree.setXMLAutoLoading(\"");
      out.print( CONTEXT_PATH);
      out.write("datastandard/standardCategory.do?action=getTree\");\r\n");
      out.write("\t\ttree.loadXML(\"");
      out.print( CONTEXT_PATH);
      out.write("datastandard/standardCategory.do?action=getTree\");\r\n");
      out.write("\r\n");
      out.write("\t\tfunction refreshItem(id){\r\n");
      out.write("\t\t\ttree.refreshItem(0);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction showMessage(msg){\r\n");
      out.write("\t\t\tvar win = dhxWins.createWindow(winName,0,0,200,120);\r\n");
      out.write("\t\t\twin.centerOnScreen();\r\n");
      out.write("\t\t\twin.denyPark();\r\n");
      out.write("\t\t\twin.denyMove();\r\n");
      out.write("\t\t\twin.denyResize();\r\n");
      out.write("\t\t\twin.button(\"minmax1\").hide();\r\n");
      out.write("\t\t\twin.button(\"park\").hide();\r\n");
      out.write("\t\t\twin.setText(\"确定\");\r\n");
      out.write("\t\t\twin.setModal(true);\r\n");
      out.write("\t\t\twin.denyMove();\r\n");
      out.write("\t\t\twin.denyResize();\r\n");
      out.write("\t\t\tvar div = \"<div><p align='center'>\" + msg + \"</p><p align='center'><input type=button onclick='closeMessage()' value='确定'/></p></div>\";\r\n");
      out.write("\t\t\twin.attachHTMLString(div);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction closeMessage(){\r\n");
      out.write("\t\t\tdhxWins.window(winName).close();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
